test

diff --git a/tools/build/buck-publish-setup b/tools/build/buck-publish-setup
--- a/tools/build/buck-publish-setup
+++ b/tools/build/buck-publish-setup
@@ -1,16 +1,13 @@
 #!/bin/bash
 
-BUCK_REF=${1:-"11-11-2016"}
-ONOS_REF=${2:-"master"}
-YANG_REF=${3:-"master"}
-DIR=$4
+BUCK_REF="11-11-2016"
+ONOS_REF="master"
+YANG_REF="master"
 
 set -x
 
-if [ -z "$4" ]; then
-    DIR=$(mktemp -d /tmp/buck-publish.XXXXX) || { echo "Failed to create temp file"; exit 1; }
-fi
 # change to tmpdir
+DIR=$(mktemp -d /tmp/buck-publish.XXXXX) || { echo "Failed to create temp file"; exit 1; }
 cd $DIR
 
 # checkout buck
@@ -25,4 +22,3 @@ set +x
 echo
 echo "Buck publish area:"
 echo "  cd $DIR"
-
